### ISSUE TITLE
Better highlighting

### ISSUE THREAD

**Issue by jens-hj** [WeetHet/typst.zed#1]
Hi, I am used to typst syntax highlighting in vscode with the typst extension, which leaves me with a lot of highlighting making it easy to visually find things:

VSCode:
![image](https://github.com/WeetHet/typst.zed/assets/33258502/2be9f24f-9c19-4a29-bdac-1b5cf0b71854)

Zed Editor:
![image](https://github.com/WeetHet/typst.zed/assets/33258502/1f97cd38-e2ef-4d42-909f-eeecfe7ccc8b)

Notice how I am using the same theme; Nanowise, and in VSCode I have a separate colour for headings, inline code, and when switching to code mode in content e.g. with `#acr("RNG")`.
Is this something that is easily achievable or is something inhibiting this goal?

**Comment by WeetHet** [comment]
I'm actually not sure. The thing is, zed uses treesitter for parsing and highlighting. As far as I know, vscode has its own API. You could try asking the VSCode extension developer if they use treesitter and if they do, ask for the grammar. You could then provide it to me, and I would update the extension to use it. I could also try looking into the grammar-defined highlights to see if I can adjust them a bit to provide better highlighting, but as I'm pretty busy now, I don't know when I would be able to do that

**Comment by Myriad-Dreamin** [comment]
vscode uses textmate grammar for instant syntax highlighting. It then uses lsp's semantic tokens api for slower semantic highlighting, with a slightly higher priority than semantic highlighting.

**Comment by WeetHet** [comment]
> vscode uses textmate grammar for instant syntax highlighting. It then uses lsp's semantic tokens api for slower semantic highlighting, with a slightly higher priority than semantic highlighting.

Oh, okay, then I don't know if I can do anything about subpar highlighting in zed :(
